### ISSUE TITLE
Create easier to understand documentation

### ISSUE THREAD

**Issue by christopherperry** [scala-android/sbt-android#115]
I'm trying to use your plugin, and step two is not clear to me:

`Create a new android project using gen-android if the plugin is installed globally.`

What is gen-android? How is it used? An example in the readme right there would be good.

**Comment by frait** [comment]
I can totally understand @christopherperry - Just saying use gen-android makes no sense at all.
An explanation like this would be more helpfull i think. At the console, type in: sbt gen-android

Then you might get an error message saying you have to use the right syntax like "Usage: gen-android <platform-target> <package-name> <name>". This is nowhere explained either - or at least not so that i could find it. You have to then type at console prompt: sbt "gen-android android-21 com.yourcompany.appname appname"

Don't forget the quotation marks! I am still trying to find the right usage for android update project. Any help here???? I am sure, your plugin is great, but pls improve the documentation!
